### PR TITLE
config reorg update

### PR DESCRIPTION
**Pull request by g2flyer**
- resolve chicken'egg of dummy keys for sgx
- rename key-related variables for more clarity and correct some of the docu
- separate key-directories for sgx-related keys and ledger-related keys

### CODE REVIEW

**Comment by g2flyer** [comment]
btw:  the source of common-config.sh currently relies on bash being the source.  This is a problem with docker as commands are run with /bin/sh (which is dash in ubuntu) and so BASH_SOURCE is not defined.    For my tests -- the only test environment i currently have where i can run run-tests is docker ... -- i resorted to the hack of (a) making sure that i source (or more precisely '.') in the build dir and then precede the SCRIPTDIR assignment with ...

if [ -z ${BASH_SOURCE} ]; then BASH_SOURCE=./foo; fi

... As said a hack but only thing i could come up.  Do you have a better idea on how to get source working also for non-bash shells?

**Comment by cmickeyb** [comment]
> btw: the source of common-config.sh currently relies on bash being the source. This is a problem with docker as commands are run with /bin/sh (which is dash in ubuntu) and so BASH_SOURCE is not defined. For my tests -- the only test environment i currently have where i can run run-tests is docker ... -- i resorted to the hack of (a) making sure that i source (or more precisely '.') in the build dir and then precede the SCRIPTDIR assignment with ...
> 
> if [ -z ${BASH_SOURCE} ]; then BASH_SOURCE=./foo; fi
> 
> ... As said a hack but only thing i could come up. Do you have a better idea on how to get source working also for non-bash shells?

Why not just explicitly invoke with /bin/bash?

**Comment by cmickeyb** [comment]
This looks very good. I only have one suggestion... the name "sgx_placebo" is a bit esoteric. How about we put the enclave signing key in build/keys and put the sgx simulator keys in build/keys/sgx_simulator and point the defaults to those. That would make it even more explicit.

**Comment by g2flyer** [comment]
> > btw: the source of common-config.sh currently relies on bash being the source. This is a problem with docker as commands are run with /bin/sh (which is dash in ubuntu) and so BASH_SOURCE is not defined. For my tests -- the only test environment i currently have where i can run run-tests is docker ... -- i resorted to the hack of (a) making sure that i source (or more precisely '.') in the build dir and then precede the SCRIPTDIR assignment with ...
> > if [ -z ${BASH_SOURCE} ]; then BASH_SOURCE=./foo; fi
> > ... As said a hack but only thing i could come up. Do you have a better idea on how to get source working also for non-bash shells?
> 
> Why not just explicitly invoke with /bin/bash?

you have to source it to get the env variable set and exported?  What one could do of course is to change the script to not set the env-variables but just to return the export statements (e.g., along the lines of what ssh-agent does) and then instead of sourcing the file you would eval it ...

**Comment by g2flyer** [comment]
> This looks very good. I only have one suggestion... the name "sgx_placebo" is a bit esoteric. How about we put the enclave signing key in build/keys and put the sgx simulator keys in build/keys/sgx_simulator and point the defaults to those. That would make it even more explicit.

I actually had initially a separate directory code_signing but after further reflection i realized that for "real" HW mode you also cannot just auto-generate that key but it would have to be a white-listed one.   Insofar my choice of putting them together and calling the directory placebo (as signing key of course is not really simulator specific).   But i don't have thaat strong feelings about naming and placement (the main thing i care about is to have the separation of root-key directories for sawtooth and the IAS keys which is somewhat orthogonal)

**Comment by cmickeyb** [comment]
Another approach with the environment variables... we can add a command line switch to the script that would dump an "eval-able" representation of the variables. This would also be useful for building your own scripts.

**Comment by g2flyer** [comment]
> Another approach with the environment variables... we can add a command line switch to the script that would dump an "eval-able" representation of the variables. This would also be useful for building your own scripts.

ok, i can add flag so it would still remain straight sourceable instead of just be eval-able.  I might as well then also add another flag which would document the variables ...

**Pull request closed without merging**
